name: actions
author: Pesys Felles
description: actions
inputs:
  team:
    description: 'Team name'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
  nais_deploy_apikey:
    description: 'Nais deploy apikey'
    required: true
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Build and push Docker image
      uses: nais/docker-build-push@v0
      id: docker-push
      with:
        team: pesys-felles
        build_secrets: github_token=${{ inputs.github_token }}
        salsa: true

    - name: Deploy to dev-gcp
      uses: nais/deploy/actions/deploy@master
      env:
        IMAGE: ${{ steps.docker-push.outputs.image }}
        APIKEY: ${{ inputs.nais_deploy_apikey }}
        CLUSTER: dev-gcp
        RESOURCE: .nais/dora-naisjob.yml
