apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: "dora-metrics-job"
  namespace: "pesys-felles"
  labels:
    team: "pesys-felles"
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
  gcp:
    bigQueryDatasets:
      - name: pensjon_dora_metrics
        permission: READWRITE
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: jira-proxy
          namespace: pesys-felles
          cluster: prod-fss
